bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
    path('addsubs/<item_id>/', views.add_subs_to_bag, name='add_subs_to_bag'),
    path(
        'removesubs/<item_id>/',
        views.remove_subs_from_bag, name='remove_subs_from_bag'),
]

kit/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.all_products, name='kit'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/',
         views.delete_product, name='delete_product'),
    path('add_category/',
         views.add_category, name='add_category'),
    path('delete_category/<int:category_id>/',
         views.delete_category, name='delete_category'),
    path('edit_category/<int:category_id>/',
         views.edit_category, name='edit_category'),
]

the_club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found, server_error


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('kit/', include('kit.urls')),
    path('bag/', include('bag.urls')),
    path('subs/', include('subs.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('clubadmin/', include('clubadmin.urls')),
    path('fixtures/', include('fixtures.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
handler500 = server_error

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from kit.models import Product
from profiles.models import UserProfile


# Create your models here.
class Order(models.Model):

    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    house_number = models.CharField(max_length=50, null=True, blank=True)
    street = models.CharField(max_length=80, null=False, blank=False)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(
        null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update the grand total every time a line item is added,
        including delivery cost.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('line_item_total'))['line_item_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100)
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Overwrite the default save to assign an order
        number if an order number doesnt exist
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):

    order = models.ForeignKey(
        Order, null=False, blank=False, on_delete=models.CASCADE,
        related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE,)
    product_size = models.CharField(max_length=10, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    line_item_total = models.DecimalField(
        max_digits=6, decimal_places=2,
        null=False, blank=False, editable=False)

    player_name = models.CharField(max_length=50, null=True, blank=True)
    team_name = models.CharField(max_length=50, null=True, blank=True)
    period = models.IntegerField(null=True, blank=True)

    def save(self, *args, **kwargs):
        """
        Overwrite the default save to set the line item total
        and update the order total
        """
        if self.period:
            self.line_item_total = self.period * settings.MONTHLY_SUBS
        else:
            self.line_item_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'''Product: {self.product.name}
        on order {self.order.order_number}'''

kit/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):

    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=254, null=False, blank=False)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    is_sub = models.BooleanField(default=False, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

kit/forms.py
from django import forms

from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'product-form'


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'product-form'

kit/views.py
from django.shortcuts import (
    render, redirect, reverse, get_object_or_404)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category
from .forms import ProductForm, CategoryForm


def all_products(request):
    """
    A view to show all products page
    """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search parameters!")
                return redirect(reverse('kit'))

            queries = Q(
                name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        "products": products,
        'search_term': query,
        'current_categories': categories,
    }
    return render(request, 'kit/products.html', context)


def product_detail(request, product_id):
    """
    A view to show individual product detail page
    """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        "product": product,
    }
    return render(request, 'kit/product_detail.html', context)


@login_required
def add_product(request):
    """
    Add a product to the shop
    """
    if not request.user.is_superuser:
        messages.error(request, '''
            Sorry. This action requires club admin access''')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Product added successfully!')
            return redirect(reverse('club_admin'))
        else:
            messages.error(request, '''
                Product has not been added. Please check the form is valid''')
    else:
        form = ProductForm()
    template = 'kit/add_product.html'
    context = {
        'form': form,
        'on_admin_page': True,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit an exisiting product
    """
    if not request.user.is_superuser:
        messages.error(request, '''
            Sorry. This action requires club admin access''')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES,  instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, f'{product.name} successfully updated')
            return redirect(reverse('club_admin'))
        else:
            messages.error(request, '''
                Product has not been updated, please check form is valid.''')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'kit/edit_product.html'
    context = {
        'form': form,
        'product': product,
        'on_admin_page': True,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete an exisiting product
    """
    if not request.user.is_superuser:
        messages.error(request, '''
            Sorry. This action requires club admin access''')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product has been deleted!')

    return redirect(reverse('edit_delete_admin'))


@login_required
def add_category(request):
    """
    Add a Product category
    """
    if not request.user.is_superuser:
        messages.error(request, '''
            Sorry. This action requires club admin access''')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save()
            messages.success(request, 'Category added successfully!')
            return redirect(reverse('club_admin'))
        else:
            messages.error(request, '''
                Category has not been added. Please check the form is valid''')
    else:
        form = CategoryForm()
    template = 'kit/add_category.html'
    context = {
        'form': form,
        'on_admin_page': True,
    }

    return render(request, template, context)


@login_required
def delete_category(request, category_id):
    """
    Delete an exisiting category
    """
    if not request.user.is_superuser:
        messages.error(request, '''
            Sorry. This action requires club admin access''')
        return redirect(reverse('home'))

    category = get_object_or_404(Category, pk=category_id)
    category.delete()
    messages.success(request, 'Category has been deleted!')

    return redirect(reverse('manage_categories'))


@login_required
def edit_category(request, category_id):
    """
    Edit an exisiting category
    """
    if not request.user.is_superuser:
        messages.error(request, '''
            Sorry. This action requires club admin access''')
        return redirect(reverse('home'))

    category = get_object_or_404(Category, pk=category_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES,  instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, f'{category.name} successfully updated')
            return redirect(reverse('manage_categories'))
        else:
            messages.error(request, '''
                Category has not been updated, please check form is valid.''')
    else:
        form = CategoryForm(instance=category)
        messages.info(request, f'You are editing {category.name}')

    template = 'kit/edit_category.html'
    context = {
        'form': form,
        'category': category,
        'on_admin_page': True,
    }

    return render(request, template, context)

kit/templates/kit/add_category.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay container-fluid"></div>
    <div class="container  mb-5 pb-5">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="mb-2 text-uppercase heading">Manage Shop</h2>
                <p class="text-uppercase text-muted">Add Product Category</p>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="{% url 'add_category' %}" method="POST" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a href="{% url 'manage_categories' %}" class="btn rounded-0 btn-dark">
                            <span>
                                <i class="fas fa-chevron-left"></i>
                            </span>
                            <span class="text-uppercase">Cancel</span>
                        </a>
                        <button type="submit" class="btn rounded-0 btn-dark text-uppercase">
                            Add Category
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-right">
                <a href="{% url 'club_admin' %}" class="btn rounded-0 btn-dark">
                    <span>
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <span class="text-uppercase">Back to Admin</span>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

kit/templates/kit/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay container-fluid"></div>
    <div class="container mb-5 pb-5">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="mb-2 text-uppercase heading">Manage Products</h2>
                <p class="text-uppercase text-muted">Add Product</p>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="{% url 'add_product' %}" method="POST" class="form product-form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a href="{% url 'kit' %}" class="btn rounded-0 btn-dark">
                            <span>
                                <i class="fas fa-chevron-left"></i>
                            </span>
                            <span class="text-uppercase">All Products</span>
                        </a>
                        <button type="submit" class="btn rounded-0 btn-dark text-uppercase">
                            List Product
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-right">
                <a href="{% url 'club_admin' %}" class="btn rounded-0 btn-dark">
                    <span>
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <span class="text-uppercase">Back to Admin</span>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

kit/templates/kit/edit_category.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay container-fluid"></div>
    <div class="container  mb-5 pb-5">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="mb-2 text-uppercase heading">Manage Shop</h2>
                <p class="text-uppercase text-muted">Edit Product Category</p>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="{% url 'edit_category' category.id %}" method="POST" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a href="{% url 'manage_categories' %}" class="btn rounded-0 btn-dark">
                            <span>
                                <i class="fas fa-chevron-left"></i>
                            </span>
                            <span class="text-uppercase">Cancel</span>
                        </a>
                        <button type="submit" class="btn rounded-0 btn-dark text-uppercase">
                            Edit Category
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-right">
                <a href="{% url 'club_admin' %}" class="btn rounded-0 btn-dark">
                    <span>
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <span class="text-uppercase">Back to Admin</span>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

kit/templates/kit/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay container-fluid"></div>
    <div class="container  mb-5 pb-5">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="mb-2 text-uppercase heading">Manage Products</h2>
                <p class="text-uppercase text-muted">Edit Product</p>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="{% url 'edit_product' product.id %}" method="POST" class="form product-form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a href="{% url 'kit' %}" class="btn rounded-0 btn-dark">
                            <span>
                                <i class="fas fa-chevron-left"></i>
                            </span>
                            <span class="text-uppercase">Cancel</span>
                        </a>
                        <button type="submit" class="btn rounded-0 btn-dark text-uppercase">
                            Update Product
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-right">
                <a href="{% url 'club_admin' %}" class="btn rounded-0 btn-dark">
                    <span>
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <span class="text-uppercase">Back to Admin</span>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

kit/templates/kit/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">

        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="overlay container-fluid"></div>
    <div class="continer  mb-5 pb-5">
        <div class="row">
            <div class="col-12 col-md-4 offset-md-2">
                <div class="row">
                    <div class="image-container my-5">
                        {% if product.image %}
                            <a href="{{ product.image.url }}" target="_blank">
                                <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                            </a>
                        {% else %}
                            <a href="">
                                <img src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}" class="card-img-top img-fluid">
                            </a>
                        {% endif %}
                    </div>
                </div>
                {% if request.user.is_superuser %}
                    <div class="row">
                        <div class="ml-5"
                            <small>
                                <a href="{% url 'edit_product' product.id %}" class="btn rounded-0 btn-sm btn-dark">Edit</a>
                            <small>
                            </small>
                                <a href="{% url 'delete_product' product.id %}" class="btn rounded-0 btn-sm btn-dark">Delete</a>
                            </small>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-12 col-md-4">
                <div class="row">
                    <div class="product-details-container mt-5 ml-5">
                        <p class="mb-0">{{ product.name }}</p>
                        <p class="lead mb-0 text-left font-weight-bold">£{{ product.price }}</p>
                        {% if product.category %}
                            <p class="small">
                                <a href="{% url 'kit' %}?category={{ product.category.name }}" class="text-muted">
                                    <i class="fa-solid fa-shirt"></i> {{ product.category.friendly_name }}
                                </a>
                            </p>
                        {% endif %}
                        <p class="mb-0">{{ product.description }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="product-details-container mb-5 ml-5">
                        <form action="{% url 'add_to_bag' product.id %}" method="POST" class="form">
                            {% csrf_token %}
                            <div class="form-row">
                                {% with product.has_sizes as s %}
                                {% if s %}
                                    <div class="col">
                                        <p><strong>Size:</strong></p>
                                        <select name="product_size" id="id_product_size" class="form-control rounded-0 w-50">
                                            <option value="kids-s6">Kids age 6 - 8</option>
                                            <option value="kids-s8">Kids age 8 - 10</option>
                                            <option value="kids-s10">Kids age 10 - 12</option>
                                            <option value="kids-s13">Kids age 13 - 15</option>
                                            <option value="ladies-s8">Ladies size 8 - 10</option>
                                            <option value="ladies-s12">Ladies size 12 - 14</option>
                                            <option value="ladies-s16">Ladies size 16 - 18</option>
                                            <option value="mens-s">Mens size S</option>
                                            <option value="mens-m" selected>Mens size M</option>
                                            <option value="mens-l">Mens size L</option>
                                        </select>
                                    </div>
                                {% endif %}
                                {% endwith %}
                                <div class="col-12">
                                    <p class="mt-3"><strong>Quantity:</strong></p>
                                    <div class="form-group w-50">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <button class="decrement-qty" data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                    <span class="icon">
                                                        <i class="fas fa-minus"></i>
                                                    </span>
                                                </button>
                                            </div>
                                            <input class="form-control qty_input" type="number"
                                                name="quantity" value="1" min="1" max="99"
                                                data-item_id="{{ product.id }}"
                                                id="id_qty_{{ product.id }}">
                                            <div class="input-group-append">
                                                <button class="increment-qty" data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                    <span class="icon">
                                                        <i class="fas fa-plus"></i>
                                                    </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <a href="{% url 'kit' %}" id="keep-shopping" class="btn rounded-0 btn-lg btn-outline-dark mb-2 product-page">
                                        <span>
                                            <i class="fas fa-chevron-left"></i>
                                        </span>
                                        <span class="text-uppercase">Keep Shopping</span>
                                    </a>
                                    <input type="submit" id="add-basket" class="btn rounded-0 btn-lg btn-dark text-uppercase mb-2 product-page" value="Add to Bag">
                                </div>
                                <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    {% include 'kit/includes/quantity_input_script.html' %}
{% endblock %}